steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/python-hello', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/python-hello']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_APP_NAME}', '--image', 'gcr.io/$PROJECT_ID/python-hello', '--region', '${_REGION}', '--platform', 'managed', '--allow-unauthenticated']
images:
- gcr.io/$PROJECT_ID/python-hello
substitutions:
    _APP_NAME: hello-world
    _REGION: us-central1